### ISSUE TITLE
Custom scan profiles fail due to read-only directory mount

### ISSUE THREAD

**Issue by atoy3731** [rancher/cis-operator#162] opened 2022-09-06 21:29 UTC
## Issue

When using a custom profile, the directory structure that is stored as a ConfigMap gets mounted into the scan pod. The scan attempts to use that same directory (the `CONFIG_DIR` in the `run_sonobuoy_plugin.sh` script). Since that directory is mounted, kubebench doesn't have write access to store the temp files it needs, which causes failed scans.

## Suggested Fix

Add something similar to the following to handle when the `CONFIG_DIR` is set to something non-standard and utilize a temporary directory:

```
# Handle read-only issue in custom benchmark mounts
if [[ "$CONFIG_DIR" != "/etc/kube-bench/cfg" ]]; then
  cp -r "$CONFIG_DIR" /tmp/cfg
  CONFIG_DIR=/tmp/cfg
fi
```

**Comment by galal-hussein** [comment] 2022-09-15 18:43
@atoy3731 I think that the cis-operator sets up a specific dir for custom config as you can see here https://github.com/rancher/cis-operator/blob/master/pkg/securityscan/job/job.go#L250-L256 it defaults the custom config to:

```
const cisoperatorapiv1.CustomBenchmarkBaseDir untyped string = "/etc/kbs/custombenchmark/cfg"
```

**Comment by prachidamle** [comment] 2022-09-21 23:20
@atoy3731 This is where the CustomBenchmarkBaseDir is defined and mounted with the configmap contents:

`const cisoperatorapiv1.CustomBenchmarkBaseDir untyped string = "/etc/kbs/custombenchmark/cfg"`

https://github.com/rancher/cis-operator/blob/master/pkg/securityscan/job/job.go#L262-L265

As seen in line https://github.com/rancher/cis-operator/blob/master/pkg/securityscan/job/job.go#L263 the ENV variable `CONFIG_DIR` is set to the above CustomBenchmarkBaseDir and that is used by the `run_sonobuoy_plugin.sh` script.

**Comment by weistonedawei** [comment] 2022-09-22 03:37
Related issue on attempt modifying read-only files is reported in issue #144.  
Since custom versions are mounted from ConfigMap with 0422 permission, files cannot modified.  In issue #144, the need to modify read only files was due to attempt to replace values in control files for k3s.  It should probably just limit modification to k3s control files.

**Comment by galal-hussein** [comment] 2022-09-26 23:14
Closing since the right directory should be used in order to use to consume the custom benchmark correctly as @prachidamle mentioned, @atoy3731 please feel free to re-open if the `/etc/kbs/custombenchmark/cfg` dir is not working as expected

**Comment by atoy3731** [comment] 2022-10-05 19:57
Thanks for looking into this and have a few more points of clarification to recreate this issue:

* This *only* affects CentOS/RHEL operating systems due to this block:
  ```
  if [[ "$(journalctl -D $JOURNAL_LOG --lines=0 2>&1 | grep -s 'No such file or directory' | wc -l)" -gt 0 ]]; then
    JOURNAL_LOG=/run/log/journal
    echo "CONFIG_DIR=$CONFIG_DIR"
    find $CONFIG_DIR -name '*.yaml' | xargs -n1 sed -i 's|/var/log/journal|/run/log/journal|'
  fi
  ```
* On CentOS/RHEL, it actual gets into that `if` statement and attempts to run that `sed` command. That command attempts to utilize the `/etc/kbs/custombenchmark/cfg` directory as its working directory.
* Since that directory is a ConfigMap mounted in, it is read-only and cannot be written to, so it fails with similar output to this:
  ```
  sed: couldn't open temporary file /etc/kbs/custombenchmark/cfg/..2022_08_16_15_04_43.1720097865/rke2-profile/seda0Al44: Read-only file system
  ```

With the suggested fix, since it is copying to a tmp directory and not using that mounted directory, it resolves the issue.

Hopefully that provides a little more clarity. Thanks again!

**Comment by weistonedawei** [comment] 2022-10-07 01:45
The workaround of copying to /tmp dir is OK.  But it should noted that copying to /tmp should be done when the custom version dir is real-only, not simply testing path name equals to  /etc/kbs/custombenchmark/cfg.  The ideal testing tool changes test cases is not very appealing.  To me, control files should not be touched by the run*.sh script.

**Comment by prachidamle** [comment] 2022-10-12 21:46
Note: With this change, We should test the custom benchmark scan usecase.

**Comment by MKlimuszka** [comment] 2022-10-13 17:58
This will be ready for test as soon as we have the chart update, which has an open PR. https://github.com/rancher/charts/pull/2149

**Comment by vivek-infracloud** [comment] 2022-10-14 10:53
@prachidamle Could you please provide steps to test this issue?

**Comment by bmdepesa** [comment] 2022-10-14 13:52
@vivek-infracloud https://docs.ranchermanager.rancher.io/explanations/integrations-in-rancher/cis-scans/custom-benchmark

**Comment by vivek-infracloud** [comment] 2022-10-17 08:08
@galal-hussein @brandond I followed the steps mentioned on the above link and see the following error message in `security-scan-runner` pod.

**Validations steps followed:**

1. Created a rancher server v2.7.0-rc3
2. Provisioned a RKE2 cluster v1.24.6+rke2r1
3. Installed a CIS Benchmark v3.0.0-rc7
4. Created a foo directory and placed all the config YAML files that are [listed here](https://github.com/rancher/security-scan/tree/master/package/cfg/rke2-cis-1.23-permissive).
5. Followed this document to run a custom scan.

**Result**
Scan does not complete and `security-scan-runner` pod shows following error.

```
time="2022-10-17T07:06:05Z" level=error msg="Result processing error (500): error handling result rancher-kube-bench/vivek-rke2-cluster-vivek-cis-custom-test-9571f21a-bwsvw: could not write body to file \"/tmp/sonobuoy/dff8cc34-897c-4f89-afce-4dcc2f8d5272/plugins/rancher-kube-bench/results/vivek-rke2-cluster-vivek-cis-custom-test-9571f21a-bwsvw/error.log\": unexpected EOF"
time="2022-10-17T07:06:05Z" level=info msg="received request" client_cert="[rancher-kube-bench]" method=PUT node=vivek-rke2-cluster-vivek-cis-custom-test-9571f21a-6wbv9 plugin_name=rancher-kube-bench url=/api/v1/results/by-node/vivek-rke2-cluster-vivek-cis-custom-test-9571f21a-6wbv9/rancher-kube-bench
```

**Comment by prachidamle** [comment] 2022-10-19 00:29
@vivek-infracloud I was not able to reproduce this problem and the custom benchmark scan passed for me on a rke cluster having k8s 1.24 as well as on k3s.

Few things to confirm:
1) I hope the `config.yaml` file that you placed inside the custom benchmark directory consists of everything mentioned in the top level config.yaml file https://github.com/rancher/security-scan/blob/master/package/cfg/config.yaml
And also add the additional changes to this file as mentioned in https://github.com/rancher/security-scan/blob/master/package/cfg/rke2-cis-1.23-permissive/config.yaml

2) The final config.yaml file should also have the custom benchmark name and components mentioned inside the "target_mapping" https://github.com/rancher/security-scan/blob/master/package/cfg/config.yaml#L222

Here are 2 examples of the custom scan directory I created for rke and k3s which I would upload as a configmap
rke: https://github.com/prachidamle/security-scan/tree/rke_custon_scan/package/cfg/foorke123
k3s: https://github.com/prachidamle/security-scan/tree/k3s_custom_scan/package/cfg/fook3s123

Please can you test this ticket and check if you are seeing the error.

**Closed** 2022-10-19 06:55 UTC
Labels: [zube]: QA Working, team/area3, team/infracloud, feature/charts-cis-benchmark, team/rke2
