### ISSUE TITLE
CIS - Provide ability to support custom profile (user skips)

### ISSUE THREAD

**Issue by maggieliu** [rancher/cis-operator#17] opened 2020-03-11 21:42 UTC
Provide ability to support custom profile (user skips)
* Ability to skip / unskip tests
* Need ability to see the "skip" status before running the scan
* Clear distinguish user skipped and Rancher skipped

**Comment by prachidamle** [comment] 2020-09-07 05:20
This has been fixed using the cis-operator and ClusterScanProfile CRD. The user skipped tests can be added to the ClusterScanProfile CR and Rancher skipped are marked as "Not Applicable" tests in the report.

Seems duplicate of https://github.com/rancher/cis-operator/issues/18

**Comment by sowmyav27** [comment] 2020-09-09 18:26
**On master-head - commit id: `343b8e19c`**

- User is able to specify tests to be skipped in a customScan profile by adding this under spec
```
spec:
  benchmarkVersion: cis-1.5
  skipTests:
    - "1.1.20"
    - "1.1.21"
```
- Permissive scan has no rancher skipped tests. Only tests marked N/A and Passed
<img width="1427" alt="Screen Shot 2020-09-09 at 11 25 46 AM" src="https://user-images.githubusercontent.com/26032343/92638533-416b0800-f28f-11ea-8f7e-ef403b593c11.png">

**Closed by sowmyav27** 2020-09-09 18:26 UTC
Labels: [zube]: To Test
